algoritmo "Tipo de Dados"
// Função : Aprendizado
// Autor : Rodrigo
// Data : 25/06/2026
// Seção de Declarações 
var

   quantidade : inteiro
   preco : real
   totalAPagar : real
   produto : caractere
   cliente : caractere
   compraEfetuada : logico

inicio

      quantidade <- 2
      preco <- 88,80
      totalAPagar <- quantidade * preco
      cliente <- "Andressa"
      produto <- "Bolsa"
      compraEfetuada <- VERDADEIRO
      
      Escreval(quantidade)
      Escreval(preco)
      Escreval(totalAPagar)
      Escreval(cliente)
      Escreval(produto)
      Escreval(compraEfetuada)
      Escreval
      Escreval
      Escreval("A Cliente ", cliente, " comprou ", quantidade, " ", produto, " e vai pagar o total de ", totalAPagar)

fimalgoritmo
