algoritmo "Funções Se - Senao"
// Função : Aprendizado
// Autor : Rodrigo
// Data : 25/06/2026
// Seção de Declarações 
var

   numero : inteiro

inicio

      //Se <expressão booleana> Entao

      //   <instruções a serem executadas caso a expressão booleana resulte em VERDADEIRO>

      //Senao

      //     <instruções a serem executadas caso a expressão booleana resulte em FALSO>

      //FimSe
      
      Escreval("Digite um numero")
      leia(numero)
      
      Se ( numero > 10 ) Entao
      
           Escreval(numero, " é MAIOR que 10.")
      
      Senao
           Escreval(numero, " é MENOR que 10.")
           
      fimSe
      
fimalgoritmo
