algoritmo "Funçoes Se - Senao com OU"
// Função : Aprendizado
// Autor : Rodrigo
// Data : 25/06/2026
// Seção de Declarações 
var

   cor : caractere

inicio

      Escreval("Digite uma cor: ")
      leia(cor)

      Se ( cor = "Azul" ) ou ( cor = "Amarelo" ) Entao

           Escreval("A cor digitada é Azul ou Amarelo")

      Senao

           Escreval("Cor Inválida!")

      FimSe

fimalgoritmo
