algoritmo "Função Se"
// Função :
// Autor :
// Data : 12/01/2022
// Seção de Declarações 
var

   numero : inteiro

inicio


      //Se <expressão booleana> Entao

      //   <instruções a serem executadas caso a expressão booleana resulte em VERDADEIRO>

      //Senao

      //     <instruções a serem executadas caso a expressão booleana resulte em FALSO>

      //FimSe
      
      Escreval("Digite um número: ")
      leia(numero)
      
      Se ( numero > 10 ) Entao

            Escreval(numero, " é MAIOR do que 10.")

      Senao
      
            Escreval(numero, " é MENOR do que 10.")
            
      FimSe


fimalgoritmo
