algoritmo "Função Se Exemplo 2"
// Função :
// Autor :
// Data : 12/01/2022
// Seção de Declarações 
var

   cor : caracter

inicio

      Escreval("Digite uma cor: ")
      leia(cor)
      
      Se (cor = "Azul") Entao
      
         Escreval("A cor digitada é Azul")
      
      Senao
      
            Se ( cor = "Amarelo" ) Entao
            
                 Escreval("A cor digitada é Amarelo")
            
            Senao
            
                 Escreval("Cor inválida!!!")
            
            FimSe
      
      FimSe

fimalgoritmo
